name: Trigger auto deployment for codetocloud-westeurope

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ codetocloud-westeurope ]
    paths:
    - '**'
    - '.github/workflows/codetocloud-westeurope-AutoDeployTrigger-11d9a23b-e2c2-4c39-9736-eca913c00028.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CODETOCLOUDWESTEUROPE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CODETOCLOUDWESTEUROPE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CODETOCLOUDWESTEUROPE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CODETOCLOUDWESTEUROPE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CODETOCLOUDWESTEUROPE_REGISTRY_PASSWORD }}
          containerAppName: codetocloud-westeurope
          resourceGroup: codetocloud-westeurope
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          


