name: Trigger auto deployment for codetocloud-westeurope-2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ codetocloud-westeurope ]
    paths:
    - '**'
    - '.github/workflows/codetocloud-westeurope-2-AutoDeployTrigger-ea3e2460-7704-4b8a-88e3-b0a484f6dead.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CODETOCLOUDWESTEUROPE2_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CODETOCLOUDWESTEUROPE2_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CODETOCLOUDWESTEUROPE2_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@ecc33566f4fffe724c058129e9760a68c5c43ad2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CODETOCLOUDWESTEUROPE2_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CODETOCLOUDWESTEUROPE2_REGISTRY_PASSWORD }}
          containerAppName: codetocloud-westeurope-2
          resourceGroup: codetocloud-westeurope-2
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          


